// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '',
    appId: '1:190872845564:web:caccb351b8eb356ac0eb79',
    messagingSenderId: '190872845564',
    projectId: 'bank-security-final',
    authDomain: 'bank-security-final.firebaseapp.com',
    storageBucket: 'bank-security-final.firebasestorage.app',
    measurementId: 'G-YH077SWNYK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '',
    appId: '1:190872845564:android:38498aec0122069ac0eb79',
    messagingSenderId: '190872845564',
    projectId: 'bank-security-final',
    storageBucket: 'bank-security-final.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '',
    appId: '1:190872845564:ios:cdf3ecf6c0824c04c0eb79',
    messagingSenderId: '190872845564',
    projectId: 'bank-security-final',
    storageBucket: 'bank-security-final.firebasestorage.app',
    iosBundleId: 'com.example.bankAlertApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlWdWuGeExz1frKA2TlcMW0ZIF4bXEsAM',
    appId: '1:190872845564:ios:cdf3ecf6c0824c04c0eb79',
    messagingSenderId: '190872845564',
    projectId: 'bank-security-final',
    storageBucket: 'bank-security-final.firebasestorage.app',
    iosBundleId: 'com.example.bankAlertApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALlvsgkrrH1r9XJfVzK4nXypq34G9HtCg',
    appId: '1:190872845564:web:99ee29149dbf309bc0eb79',
    messagingSenderId: '190872845564',
    projectId: 'bank-security-final',
    authDomain: 'bank-security-final.firebaseapp.com',
    storageBucket: 'bank-security-final.firebasestorage.app',
    measurementId: 'G-Q72ZME2ZH7',
  );
}
